/**
 * demo-data.js — Demo Data Generator
 * ====================================
 * Generates realistic-looking OHLCV candle data, trading signals,
 * paper trades, and watchlist entries for demo / development mode.
 *
 * The random walk model uses configurable trend, volatility, and volume
 * parameters to produce believable price action.
 *
 * Task ID: 2-a
 */

import {
  SIGNAL_DIRECTIONS,
  STRATEGY_TYPES,
  INDICATOR_TYPES,
  TRADE_STATUS,
  TRADE_EXIT_REASON,
  TIMEFRAMES,
  TIMEFRAME_MS,
} from './types.js';
import { generateId } from './utils.js';

// ---------------------------------------------------------------------------
// Symbol Presets — Realistic price ranges for demo data
// ---------------------------------------------------------------------------

/**
 * Predefined symbols with price ranges used by the demo generator.
 * Prices are approximate mid-2024 market rates.
 */
export const DEMO_SYMBOLS = Object.freeze({
  BTCUSDT:  { base: 'BTC',  quote: 'USDT', basePrice: 67_000,   volatility: 0.018, volume: 15_000 },
  ETHUSDT:  { base: 'ETH',  quote: 'USDT', basePrice: 3_500,    volatility: 0.022, volume: 80_000 },
  SOLUSDT:  { base: 'SOL',  quote: 'USDT', basePrice: 172,      volatility: 0.035, volume: 200_000 },
  BNBUSDT:  { base: 'BNB',  quote: 'USDT', basePrice: 600,      volatility: 0.020, volume: 50_000 },
  XRPUSDT:  { base: 'XRP',  quote: 'USDT', basePrice: 0.62,     volatility: 0.028, volume: 500_000 },
  ADAUSDT:  { base: 'ADA',  quote: 'USDT', basePrice: 0.45,     volatility: 0.032, volume: 300_000 },
  DOGEUSDT: { base: 'DOGE', quote: 'USDT', basePrice: 0.165,    volatility: 0.040, volume: 1_000_000 },
  AVAXUSDT: { base: 'AVAX', quote: 'USDT', basePrice: 38,       volatility: 0.030, volume: 120_000 },
});

/** Default symbol keys for iteration. */
export const DEMO_SYMBOL_LIST = Object.freeze(Object.keys(DEMO_SYMBOLS));

// ---------------------------------------------------------------------------
// Candle Generation — Random Walk with Trend
// ---------------------------------------------------------------------------

/**
 * Generate an array of realistic OHLCV candle data.
 *
 * The algorithm:
 *  1. Start from `basePrice` at a point in the past.
 *  2. Each candle is generated by:
 *     - Computing a random drift (slight trend bias).
 *     - Applying Gaussian-like noise scaled by volatility.
 *     - Deriving open from previous close.
 *     - Deriving high/low from the range with guaranteed structure.
 *     - Generating volume with realistic base + spikes.
 *
 * @param {string} symbol    — e.g. "BTCUSDT"
 * @param {string} timeframe — e.g. "1h", "4h", "1d"
 * @param {number} [count=500]
 * @returns {Array<{time: number, open: number, high: number, low: number, close: number, volume: number}>}
 */
export function generateDemoCandles(symbol, timeframe, count = 500) {
  const preset = DEMO_SYMBOLS[symbol.toUpperCase()];
  if (!preset) {
    console.warn(`[DemoData] Unknown symbol "${symbol}", using BTCUSDT defaults.`);
    return generateDemoCandles('BTCUSDT', timeframe, count);
  }

  const { basePrice, volatility, volume: baseVolume } = preset;
  const tfMs = TIMEFRAME_MS[timeframe] ?? 3_600_000;
  const now = Math.floor(Date.now() / 1000) * 1000; // truncate to second

  // Start `count` candles ago
  const endTime = now;
  const startTime = endTime - (count * tfMs);

  const candles = [];
  let price = basePrice * (0.85 + Math.random() * 0.15); // random starting offset

  // Trend parameters — slowly drift over the dataset
  let trend = (Math.random() - 0.5) * 0.002; // initial trend bias

  for (let i = 0; i < count; i++) {
    const time = startTime + (i * tfMs);

    // Update trend periodically (mean-reverting)
    if (i % 50 === 0) {
      trend = (Math.random() - 0.5) * 0.003;
    }

    // Generate percentage change with trend + noise
    // Use Box-Muller for Gaussian-like noise
    const u1 = Math.random();
    const u2 = Math.random();
    const gaussian = Math.sqrt(-2 * Math.log(u1 || 0.0001)) * Math.cos(2 * Math.PI * u2);
    const noise = gaussian * volatility * 0.4; // scale to ~40% of daily vol per candle
    const change = trend + noise;

    const open = price;
    const close = open * (1 + change);

    // Compute high/low — wicks extend beyond the body
    const range = Math.abs(close - open);
    const upperWick = Math.abs(gaussian) * volatility * 0.3 * open;
    const lowerWick = Math.abs(gaussian * 0.7 + (Math.random() - 0.5) * 0.5) * volatility * 0.3 * open;

    const high = Math.max(open, close) + upperWick;
    const low  = Math.min(open, close) - lowerWick;

    // Ensure structural integrity: high >= max(open,close), low <= min(open,close)
    const adjustedHigh = Math.max(high, Math.max(open, close) + 0.001 * open);
    const adjustedLow  = Math.min(low,  Math.min(open, close) - 0.001 * open);

    // Volume — base volume with occasional spikes
    const volSpike = Math.random() < 0.05 ? (2 + Math.random() * 5) : 1;
    const volTrend = 1 + Math.sin(i / 80) * 0.3; // seasonal volume pattern
    const volume = baseVolume * volSpike * volTrend * (0.7 + Math.random() * 0.6);

    candles.push({
      time,
      open:  parseFloat(open.toFixed(8)),
      high:  parseFloat(adjustedHigh.toFixed(8)),
      low:   parseFloat(adjustedLow.toFixed(8)),
      close: parseFloat(close.toFixed(8)),
      volume: parseFloat(volume.toFixed(2)),
    });

    price = close;
  }

  return candles;
}

// ---------------------------------------------------------------------------
// Signal Generation
// ---------------------------------------------------------------------------

/**
 * Generate realistic demo trading signals.
 *
 * @param {number} [count=20]
 * @returns {Array<object>}
 */
export function generateDemoSignals(count = 20) {
  const signals = [];
  const symbols = DEMO_SYMBOL_LIST;
  const directions = Object.values(SIGNAL_DIRECTIONS);
  const strategies = Object.values(STRATEGY_TYPES);

  const now = Date.now();

  for (let i = 0; i < count; i++) {
    const symbol = symbols[Math.floor(Math.random() * symbols.length)];
    const preset = DEMO_SYMBOLS[symbol];
    const direction = directions[Math.floor(Math.random() * directions.length)];
    const strategy = strategies[Math.floor(Math.random() * strategies.length)];
    const score = direction === SIGNAL_DIRECTIONS.NO_TRADE
      ? Math.floor(Math.random() * 30)
      : Math.floor(30 + Math.random() * 70);
    const timeframe = TIMEFRAMES[Math.floor(Math.random() * TIMEFRAMES.length)];

    // Build a list of relevant indicators
    const indicatorList = [];
    const allIndicators = Object.values(INDICATOR_TYPES);
    const indicatorCount = 2 + Math.floor(Math.random() * 4);
    const shuffled = allIndicators.sort(() => Math.random() - 0.5);
    for (let j = 0; j < indicatorCount && j < shuffled.length; j++) {
      indicatorList.push(shuffled[j]);
    }

    // Generate price around the symbol's base
    const priceOffset = (Math.random() - 0.5) * 0.1;
    const price = preset.basePrice * (1 + priceOffset);

    signals.push({
      id:          generateId(),
      symbol,
      timeframe,
      direction,
      strategy,
      score,
      price:       parseFloat(price.toFixed(8)),
      timestamp:   now - (i * 300_000) + Math.floor(Math.random() * 60_000),
      indicators:  indicatorList,
      // Optional fields
      stopLoss:    direction === SIGNAL_DIRECTIONS.NO_TRADE ? null : parseFloat((price * (1 - 0.02 * (direction === 'long' ? 1 : -1))).toFixed(8)),
      takeProfit:  direction === SIGNAL_DIRECTIONS.NO_TRADE ? null : parseFloat((price * (1 + 0.04 * (direction === 'long' ? 1 : -1))).toFixed(8)),
      reasoning:   generateReasoning(direction, strategy, symbol),
    });
  }

  // Sort by timestamp descending (most recent first)
  signals.sort((a, b) => b.timestamp - a.timestamp);
  return signals;
}

/**
 * Generate a plausible reasoning string for a demo signal.
 * @private
 */
function generateReasoning(direction, strategy, symbol) {
  const reasons = {
    ema_trend: [
      'Price crossing above 50/200 EMA with strong volume confirmation.',
      'EMA alignment showing clear uptrend; pullback to 21 EMA support.',
      'Bearish EMA crossover confirmed on higher timeframe.',
    ],
    rsi_pullback: [
      `RSI bounced from oversold zone (28) with bullish divergence on ${symbol}.`,
      'RSI showing overbought conditions with bearish divergence.',
      'RSI neutral zone — no clear pullback setup at this time.',
    ],
    macd_momentum: [
      'MACD histogram turning positive with signal line crossover.',
      'MACD bearish crossover; momentum shifting to downside.',
      'MACD histogram declining — momentum weakening.',
    ],
    breakout_retest: [
      'Price broke above key resistance and successfully retested the breakout level.',
      'Breakdown below support confirmed with volume spike; retest acting as resistance.',
      'Consolidation range — no clear breakout detected.',
    ],
    vwap_volume: [
      'Price above VWAP with increasing volume — institutional buying detected.',
      'Price below VWAP with declining volume — distribution phase.',
      'Price trading around VWAP — mixed volume signals.',
    ],
    market_structure: [
      'Higher highs and higher lows confirmed — bullish market structure intact.',
      'Lower lows forming — bearish structure breakdown in progress.',
      'Market structure neutral; range-bound between key levels.',
    ],
    bollinger_squeeze: [
      'Bollinger Bands squeezing tightly — explosive move imminent.',
      'Price expanding outside bands after prolonged squeeze — continuation expected.',
      'Bands at normal width — no squeeze condition present.',
    ],
  };

  const pool = reasons[strategy] || reasons.ema_trend;
  return pool[Math.floor(Math.random() * pool.length)];
}

// ---------------------------------------------------------------------------
// Trade Generation
// ---------------------------------------------------------------------------

/**
 * Generate demo paper trading history.
 *
 * @param {number} [count=15]
 * @returns {Array<object>}
 */
export function generateDemoTrades(count = 15) {
  const trades = [];
  const symbols = DEMO_SYMBOL_LIST;
  const directions = [SIGNAL_DIRECTIONS.LONG, SIGNAL_DIRECTIONS.SHORT];
  const strategies = Object.values(STRATEGY_TYPES);
  const exitReasons = Object.values(TRADE_EXIT_REASON);

  const now = Date.now();

  for (let i = 0; i < count; i++) {
    const symbol = symbols[Math.floor(Math.random() * symbols.length)];
    const preset = DEMO_SYMBOLS[symbol];
    const direction = directions[Math.floor(Math.random() * directions.length)];
    const strategy = strategies[Math.floor(Math.random() * strategies.length)];

    // Entry price
    const entryOffset = (Math.random() - 0.5) * 0.05;
    const entryPrice = preset.basePrice * (1 + entryOffset);

    // Random PnL between -8% and +12%
    const pnlPercent = (Math.random() - 0.4) * 20;
    const pnlSign = direction === SIGNAL_DIRECTIONS.LONG ? 1 : -1;
    const exitPrice = entryPrice * (1 + (pnlPercent / 100) * pnlSign);

    // Quantity — random USDT amount divided by price
    const usdAmount = 100 + Math.random() * 900;
    const quantity = usdAmount / entryPrice;
    const pnl = (exitPrice - entryPrice) * quantity * (direction === SIGNAL_DIRECTIONS.LONG ? 1 : -1);

    // Determine if open or closed
    const isOpen = Math.random() < 0.2; // 20% chance still open
    const entryTime = now - ((i + 1) * 600_000) + Math.floor(Math.random() * 300_000);

    trades.push({
      id:          generateId(),
      symbol,
      direction,
      strategy,
      entryPrice:  parseFloat(entryPrice.toFixed(8)),
      exitPrice:   isOpen ? null : parseFloat(exitPrice.toFixed(8)),
      quantity:    parseFloat(quantity.toFixed(8)),
      stopLoss:    parseFloat((entryPrice * (1 - 0.025 * (direction === 'long' ? 1 : -1))).toFixed(8)),
      takeProfit:  parseFloat((entryPrice * (1 + 0.05 * (direction === 'long' ? 1 : -1))).toFixed(8)),
      status:      isOpen ? TRADE_STATUS.OPEN : TRADE_STATUS.CLOSED,
      entryTime,
      exitTime:    isOpen ? null : entryTime + Math.floor(Math.random() * 1_200_000) + 60_000,
      pnl:         isOpen ? null : parseFloat(pnl.toFixed(2)),
      pnlPercent:  isOpen ? null : parseFloat(pnlPercent.toFixed(2)),
      exitReason:  isOpen ? null : exitReasons[Math.floor(Math.random() * exitReasons.length)],
    });
  }

  // Sort by entry time descending
  trades.sort((a, b) => b.entryTime - a.entryTime);
  return trades;
}

// ---------------------------------------------------------------------------
// Watchlist Generation
// ---------------------------------------------------------------------------

/**
 * Generate a demo watchlist — a subset of the predefined symbols.
 *
 * @returns {Array<string>}
 */
export function generateDemoWatchlist() {
  // Return a random 5–7 subset of symbols
  const shuffled = [...DEMO_SYMBOL_LIST].sort(() => Math.random() - 0.5);
  const count = 5 + Math.floor(Math.random() * 3); // 5-7
  return shuffled.slice(0, count);
}

// ---------------------------------------------------------------------------
// Full Demo Dataset
// ---------------------------------------------------------------------------

/**
 * Generate a complete demo dataset for the application.
 * Useful for initialising the entire UI in demo mode.
 *
 * @param {object} [options]
 * @param {string} [options.defaultSymbol='BTCUSDT']
 * @param {string} [options.defaultTimeframe='1h']
 * @param {number} [options.candleCount=500]
 * @returns {object}
 */
export function generateFullDemoDataset(options = {}) {
  const {
    defaultSymbol = 'BTCUSDT',
    defaultTimeframe = '1h',
    candleCount = 500,
  } = options;

  const watchlist = generateDemoWatchlist();
  const candles = generateDemoCandles(defaultSymbol, defaultTimeframe, candleCount);
  const signals = generateDemoSignals(20);
  const trades = generateDemoTrades(15);

  return {
    candles,
    signals,
    trades,
    watchlist,
    symbol: defaultSymbol,
    timeframe: defaultTimeframe,
  };
}
